Get http://localhost:4000/products
###

POST http://localhost:4000/users
Content-Type: application/json
{
    "fullname": "Yaseen Jattiem",
    "email": "yaseen@gmail.com",
    "password": "1234567890"
}